### ISSUE TITLE
[bug]: compilation error: undefined: atomic.Uint64 , for 0.16.0-rc2

### ISSUE THREAD

**Issue by xmrk-btc** [lightningnetwork/lnd#7495]
### Background

Getting compilation error after running make clean && make:
```
Building debug lnd and lncli.
go build -v -tags="dev" -o lnd-debug -gcflags "all=-N -l" -ldflags " -X github.com/lightningnetwork/lnd/build.Commit=v0.16.0-beta.rc2" github.com/lightningnetwork/lnd/cmd/lnd
github.com/lightningnetwork/lnd/discovery
# github.com/lightningnetwork/lnd/discovery
discovery/gossiper.go:644:15: undefined: atomic.Uint64
make: *** [Makefile:91: build] Error 2

```

 Version 0.16.0-rc1 compiles fine.

### Your environment

Ubuntu 22.04, Rasberry Pi 4, arm64, GOVERSION="go1.18.1"  

And per release notes, build with go1.18.1 should be supported, but perhaps it is not (just guessing).
